WIP Raj/camera
brilliantlabsAR/frame-codebase pull request #158
Opened 2024-03-27 13:29 UTC by siliconwitch

2024-03-27 21:38 UTC, rmetchev requested changes

2024-03-27 21:38 UTC, rmetchev commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    input logic [7:0] quality_factor_in,
Quality is controlled by a **4-bit signed 2's complement** compression factor `cf[3:0]`.
The table below shows  compression factors, the QF equivalents and the actual quantization table scaling factors.
-8: QF = 99.8, scale = 2^-8
-7: QF = 99.6, scale = 2^-7
-6: QF = 99.2, scale = 2^-6
-5: QF = 98.4, scale = 2^-5
-4: QF = 96.9, scale = 2^-4
-3: QF = 93.8, scale = 2^-3
-2: QF = 87.5, scale = 2-2
-1: QF = 75.0, scale = 2^-1
0: QF = 50.0, scale = 2^0
1: QF = 25.0, scale = 2^1
2: QF = 12.5, scale = 2^2
3: QF = 6.2, scale = 2^3
4: QF = 3.1, scale = 2^4
5: QF = 1.6, scale = 2^5
6: QF = 0.8, scale = 2^6
7: QF = 0.4, scale = 2^7`

2024-03-27 21:38 UTC, rmetchev commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    output logic [127:0] data_out,
Missing: Qualifier for valid data:
`output logic data_valid_out,`

2024-03-27 21:38 UTC, rmetchev commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    output logic [3:0] bytes_valid_out,
Pls remove 'valid' from signal name to avoid confusion with `data_valid_out`:
`output logic [3:0] bytes_out,`

2024-03-27 21:38 UTC, rmetchev commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    output logic image_valid_out
When `image_valid_out == 1`, size of compressed data is `address_out + bytes_out`.

`bytes_out` can be ignored and assumed to be 16 (rounded up to 16), in that case size of compressed data  will be `address_out + 16`.  Invalid bytes in `data_out` are padded with 0xFF, and the resulting compressed data will be `(16 - bytes_out)` larger than necessary.

2024-03-27 21:38 UTC, rmetchev commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +module jpeg (
Pls rename to jenc_top:
`module jenc_top (`

2024-03-27 23:47 UTC, rmetchev commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    input logic [10:0] y_size_in,
Pushed subtraction down to encoder, so only width of y_size_in needs to change to 10.

2024-03-27 23:47 UTC, rmetchev commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    input logic [9:0] blue_data_in,
Pushed quantization down to encoder.

2024-03-28 15:30 UTC, siliconwitch commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    input logic [10:0] y_size_in,
done

2024-03-28 15:37 UTC, siliconwitch commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    input logic [7:0] quality_factor_in,
done

2024-03-28 15:55 UTC, siliconwitch commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    input logic clock_in,
done

2024-03-28 15:58 UTC, siliconwitch commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    output logic [127:0] data_out,
done

2024-03-28 15:58 UTC, siliconwitch commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +    output logic [3:0] bytes_valid_out,
removed bytes_out

2024-03-28 16:03 UTC, siliconwitch commented on source/fpga/modules/camera/jpeg/jpeg.sv
> +module jpeg (
I'm trying to avoid abbreviations where possible. Convention across the rest of the project is also that any folder called `module` containing `module.sv` is assumed to be `module_top` 

Okay to keep it as `jpeg`? or `jpeg_encoder`?

2024-03-28 16:11 UTC, merged